quarkus:
  native:
    resources:
      includes: ../treasure-inc-conf/server/conf/.maestro.env
  http:
    port: 8082
    test-port: 8083
    test-timeout: 10s
  datasource:
    username: treasure_inc
    password: 
    jdbc: 
      url: jdbc:postgresql://localhost:5432/treasure_inc
      max-size: 16
  hibernate-orm:
    database:
      generation: none
  mailer:
    from: support@treasure-inc.fr
    host:
    port:
    username:
    password:

maestro:
  apikey:
  adminEmail:

"%dev":
  quarkus:
    log: 
      console:
        json: false

"%test":
  quarkus:
    datasource:
      db-kind: h2
      username: treasure_inc_test
      password:
      jdbc:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
        max-size: 16
    hibernate-orm:
        database:
            generation: drop-and-create
    log:
      console:
        json: false
  maestro:
    apikey: TESTAPIKEY
    adminEmail: test.admin.maestro@yopmail.com