quarkus:
  native:
    resources:
      includes: ../treasure-inc-conf/server/conf/.maestro.env
  http:
    port: 8082
  datasource:
    username: treasure_inc
    password: 
    jdbc: 
      url: jdbc:postgresql://localhost:5432/treasure_inc
      max-size: 16
  hibernate-orm:
    database:
      generation: none
"%dev":
  quarkus:
    log: 
      console:
        json: false
"%test":
  quarkus:
    log: 
      console:
        json: false
maestro:
  apikey:
