quarkus:
  native:
    resources:
      includes: ../treasure-inc-conf/server/conf/.maestro.env
  http:
    port: 8082
    test-port: 8083
    test-timeout: 10s
  hibernate-orm:
    database:
      generation: none
  mailer:
    from: support@treasure-inc.fr
    host:
    port:
    username:
    password:

maestro:
  apikey:
  adminEmail:

"%dev":
  quarkus:
    datasource:
      username: treasure_inc
      password:
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/treasure_inc
        max-size: 16
    log: 
      console:
        json: false

"%test":
  quarkus:
    hibernate-orm:
        database:
            generation: drop-and-create
    log:
      console:
        json: false
  maestro:
    apikey: TESTAPIKEY
    adminEmail: test.admin.maestro@yopmail.com

"%prod":
  quarkus:
    datasource:
      username: treasure_inc
      password:
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/treasure_inc
        max-size: 16