name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: chmod +x mvnw && docker build . --file src/main/docker/Dockerfile --tag 582629265664.dkr.ecr.eu-west-3.amazonaws.com/treasure-inc-maestro:$(date +%s)
