
name: Maestro Docker native Image

on: workflow_dispatch

env:
  AWS_REGION: eu-west-3
  ECR_REPOSITORY: 582629265664.dkr.ecr.eu-west-3.amazonaws.com/treasure-inc-maestro

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Get version
      id: get_version
      run: |
        VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
        echo "::set-output name=version::$VERSION"
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ steps.get_version.outputs.version }}-${{ github.sha }}
      run: |
        chmod +x mvnw 
        docker build . --file src/main/docker/Dockerfile --tag $ECR_REPOSITORY:$IMAGE_TAG
    - name: Push the Docker image
      IMAGE_TAG: ${{ steps.get_version.outputs.version }}-${{ github.sha }}
      run: |
        docker push $ECR_REPOSITORY:$IMAGE_TAG